eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: servicezuul
zuul:
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 60000
  routes:
    api-a:
      path: /api-a/**
      serviceId: serviceribbon
    api-b:
      path: /api-b/**
      serviceId: servicefeign

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000